// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleConsole.API.Data;

#nullable disable

namespace VehicleConsole.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119184953_AddVehicleRoutesAndRoutePoints")]
    partial class AddVehicleRoutesAndRoutePoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleConsole.API.Models.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("RoutePoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 39.933399999999999,
                            Longitude = 32.859699999999997,
                            Order = 1,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 39.927199999999999,
                            Longitude = 32.864400000000003,
                            Order = 2,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 39.9208,
                            Longitude = 32.854100000000003,
                            Order = 3,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 39.914999999999999,
                            Longitude = 32.840000000000003,
                            Order = 4,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 39.909999999999997,
                            Longitude = 32.829999999999998,
                            Order = 5,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 39.905000000000001,
                            Longitude = 32.82,
                            Order = 6,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 39.899999999999999,
                            Longitude = 32.810000000000002,
                            Order = 7,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 39.895000000000003,
                            Longitude = 32.799999999999997,
                            Order = 8,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 39.890000000000001,
                            Longitude = 32.789999999999999,
                            Order = 9,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 39.884999999999998,
                            Longitude = 32.780000000000001,
                            Order = 10,
                            RouteId = 1
                        });
                });

            modelBuilder.Entity("VehicleConsole.API.Models.VehicleRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ankara City Route"
                        });
                });

            modelBuilder.Entity("VehicleConsole.API.Models.VehicleSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Angle")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FogLights")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headlights")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VehicleSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Angle = 11,
                            FogLights = "Front Fog",
                            Headlights = "Auto"
                        });
                });

            modelBuilder.Entity("VehicleConsole.API.Models.RoutePoint", b =>
                {
                    b.HasOne("VehicleConsole.API.Models.VehicleRoute", "Route")
                        .WithMany("Points")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("VehicleConsole.API.Models.VehicleRoute", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
